2025-07-15T16:08:44|INFO|FancyApp|proposed values default_settings.ini
2025-07-15T16:08:44|INFO|FancyApp|settings loaded from default_settings.ini
2025-07-15T16:08:50|CRITICAL|root|Unhandled exception: Traceback (most recent call last):
  File "C:\Users\Auden\AppData\Local\Programs\Python\Python312\Lib\site-packages\ScopeFoundry\measurement.py", line 38, in run
    self.measurement._thread_run()
  File "C:\Users\Auden\AppData\Local\Programs\Python\Python312\Lib\site-packages\ScopeFoundry\measurement.py", line 251, in _thread_run
    self.run()
  File "c:\Users\Auden\Dropbox\PC (2)\Documents\Jupyter\phys 111b\Segre-Internship\GMAMicroscope\measurements\scope_read.py", line 36, in run
    for i in range(self.settings["sampling_period"]):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'float' object cannot be interpreted as an integer

2025-07-15T16:09:09|INFO|FancyApp|on_close
2025-07-15T16:09:09|INFO|FancyApp|disconnecting ni_dac
2025-07-15T16:09:09|INFO|FancyApp|disconnecting ads
